import manifest from "@/content/directory/manifest.json";

import channels from "@/content/directory/channels.json";
import courses from "@/content/directory/courses.json";
import schools from "@/content/directory/schools.json";
import books from "@/content/directory/books.json";
import studios from "@/content/directory/studios.json";
import reference from "@/content/directory/reference.json";
import awards from "@/content/directory/awards.json";
import tools from "@/content/directory/tools.json";
import freebies from "@/content/directory/freebies.json";
import community from "@/content/directory/community.json";
import glossary from "@/content/directory/glossary.json";
import timeline from "@/content/directory/timeline.json";

// The Directory is a database, not copy. It lives in content/directory/, generated by
// scripts/directory/build.mjs from the TSV sources — so the Studio, which rewrites
// content/site.json wholesale, can never clobber it. The Directory's *framing copy*
// does live in site.json and is edited in the Studio like everything else.
//
// Import this module from server components only: it pulls in every collection,
// and studios.json alone is a few hundred kilobytes. Collection pages pass the
// one collection they need down to the client component as a prop, so Next
// splits the payload per route. The client-side hub imports the manifest
// directly instead — see DirectoryPage.

export type Facet = {
  key: string;
  label: string;
  values: { value: string; count: number }[];
};

export type DirectoryEntry = {
  id: string;
  name: string;
  href?: string;
  note?: string;
  meta?: string;
  facets: Record<string, string[]>;
};

export type DirectoryCollection = {
  id: string;
  shelf: string;
  name: string;
  letter: string;
  blurb: string;
  /** "notion" for rows exported from the club's own databases, "seed" for
   *  entries written from knowledge and not yet link-checked. */
  source: string;
  /** Verb on each row's outbound link. Empty for collections that don't link out. */
  action: string;
  count: number;
  facets: Facet[];
  entries: DirectoryEntry[];
};

export type Shelf = { id: string; name: string; note: string };

export type ManifestCollection = {
  id: string;
  shelf: string;
  name: string;
  letter: string;
  blurb: string;
  source: string;
  count: number;
  facets: string[];
};

const collections = [
  channels,
  courses,
  schools,
  books,
  studios,
  reference,
  awards,
  tools,
  freebies,
  community,
  glossary,
  timeline,
] as DirectoryCollection[];

export const shelves = manifest.shelves as Shelf[];
export const directoryTotal = manifest.total as number;
export const manifestCollections = manifest.collections as ManifestCollection[];

export function getCollection(id: string): DirectoryCollection | undefined {
  return collections.find((c) => c.id === id);
}

export function collectionIds(): string[] {
  return collections.map((c) => c.id);
}
