// The emoji the Scheduler's picker offers, with the words you'd search them
// by. A curated few hundred rather than the whole Unicode table: a picker is
// for the twenty you actually use and the search box for the rest of these,
// and a dependency to ship all four thousand would be the first library the
// deployed app carried. Typed in plain rows so adding one is one line.
//
// Each row is [glyph, name, ...aliases]; the group is the heading it sits
// under in the picker.

export type EmojiGroup = { label: string; rows: string[][] };

export const EMOJI: EmojiGroup[] = [
  {
    label: "Faces",
    rows: [
      ["😀", "grinning", "smile", "happy"],
      ["😃", "big smile", "happy"],
      ["😄", "smiling eyes", "happy"],
      ["😁", "beaming", "grin"],
      ["😆", "laughing", "haha"],
      ["😅", "sweat smile", "phew"],
      ["🤣", "rolling laughing", "rofl"],
      ["😂", "tears of joy", "lol"],
      ["🙂", "slight smile"],
      ["🙃", "upside down"],
      ["😉", "wink"],
      ["😊", "blush", "smiling"],
      ["😇", "halo", "angel"],
      ["🥰", "hearts face", "love"],
      ["😍", "heart eyes", "love"],
      ["🤩", "star struck", "wow"],
      ["😘", "kiss"],
      ["😋", "yum", "tasty"],
      ["😛", "tongue"],
      ["😜", "winking tongue", "silly"],
      ["🤪", "zany", "crazy"],
      ["🤔", "thinking", "hmm"],
      ["🤨", "raised eyebrow", "suspicious"],
      ["😐", "neutral"],
      ["😑", "expressionless"],
      ["😶", "no mouth", "quiet"],
      ["🙄", "eye roll"],
      ["😏", "smirk"],
      ["😒", "unamused", "meh"],
      ["😬", "grimace", "awkward"],
      ["🤥", "lying", "pinocchio"],
      ["😌", "relieved", "calm"],
      ["😔", "pensive", "sad"],
      ["😪", "sleepy"],
      ["😴", "sleeping", "zzz"],
      ["😷", "mask", "sick"],
      ["🤒", "thermometer", "sick"],
      ["🤯", "mind blown", "exploding head"],
      ["🥳", "party", "celebrate"],
      ["🥸", "disguise"],
      ["😎", "sunglasses", "cool"],
      ["🤓", "nerd", "glasses"],
      ["🧐", "monocle", "inspect"],
      ["😕", "confused"],
      ["😟", "worried"],
      ["🙁", "frown", "sad"],
      ["😮", "open mouth", "surprised"],
      ["😯", "hushed"],
      ["😲", "astonished", "shocked"],
      ["😳", "flushed", "embarrassed"],
      ["🥺", "pleading", "puppy eyes"],
      ["😢", "crying", "tear"],
      ["😭", "sobbing", "loudly crying"],
      ["😱", "scream", "fear"],
      ["😤", "huffing", "triumph"],
      ["😡", "angry", "rage"],
      ["🤬", "cursing", "swearing"],
      ["💀", "skull", "dead"],
      ["☠️", "skull crossbones"],
      ["💩", "poop"],
      ["🤡", "clown"],
      ["👻", "ghost"],
      ["👽", "alien"],
      ["🤖", "robot", "bot"],
      ["🎃", "pumpkin", "halloween"],
      ["😺", "cat smile"],
      ["🙈", "see no evil", "monkey"],
      ["🙉", "hear no evil", "monkey"],
      ["🙊", "speak no evil", "monkey"],
    ],
  },
  {
    label: "Hands",
    rows: [
      ["👋", "wave", "hello", "bye"],
      ["🤚", "raised back of hand"],
      ["✋", "raised hand", "stop"],
      ["🖖", "vulcan", "spock"],
      ["👌", "ok", "perfect"],
      ["🤌", "pinched fingers", "italian"],
      ["🤏", "pinch", "small"],
      ["✌️", "peace", "victory"],
      ["🤞", "crossed fingers", "luck"],
      ["🤟", "love you"],
      ["🤘", "rock", "horns"],
      ["🤙", "call me", "shaka"],
      ["👈", "point left"],
      ["👉", "point right"],
      ["👆", "point up"],
      ["👇", "point down", "below"],
      ["☝️", "index up", "one"],
      ["👍", "thumbs up", "yes", "like"],
      ["👎", "thumbs down", "no"],
      ["✊", "fist"],
      ["👊", "punch", "fist bump"],
      ["👏", "clap", "applause"],
      ["🙌", "raised hands", "hooray"],
      ["🤲", "palms up"],
      ["🤝", "handshake", "deal"],
      ["🙏", "pray", "thanks", "please"],
      ["✍️", "writing", "pen"],
      ["💪", "flex", "strong", "muscle"],
      ["🧠", "brain", "think"],
      ["👀", "eyes", "look"],
      ["👁️", "eye"],
      ["🫶", "heart hands"],
    ],
  },
  {
    label: "Hearts and symbols",
    rows: [
      ["❤️", "red heart", "love"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["💔", "broken heart"],
      ["❤️‍🔥", "heart on fire"],
      ["💯", "hundred", "100"],
      ["💥", "boom", "collision"],
      ["💫", "dizzy", "star"],
      ["⭐", "star"],
      ["🌟", "glowing star"],
      ["✨", "sparkles", "new", "shiny"],
      ["⚡", "lightning", "zap", "fast"],
      ["🔥", "fire", "hot", "lit"],
      ["💧", "droplet", "water"],
      ["🌈", "rainbow"],
      ["☀️", "sun"],
      ["🌙", "moon", "night"],
      ["☁️", "cloud"],
      ["❄️", "snowflake", "cold"],
      ["✅", "check", "done", "yes"],
      ["☑️", "checkbox"],
      ["✔️", "check mark"],
      ["❌", "cross", "no", "wrong"],
      ["❓", "question"],
      ["❗", "exclamation", "important"],
      ["⚠️", "warning"],
      ["🚫", "prohibited", "no"],
      ["♻️", "recycle"],
      ["🔁", "repeat", "loop"],
      ["🔄", "refresh", "cycle"],
      ["➡️", "arrow right", "next"],
      ["⬅️", "arrow left", "back"],
      ["⬆️", "arrow up"],
      ["⬇️", "arrow down"],
      ["↗️", "up right", "growth"],
      ["🔗", "link", "chain"],
      ["🔔", "bell", "notification"],
      ["🔒", "lock", "private"],
      ["🔓", "unlock"],
      ["🔑", "key"],
      ["♾️", "infinity"],
      ["#️⃣", "hash", "hashtag"],
      ["🆕", "new"],
      ["🆓", "free"],
      ["🔝", "top"],
      ["🔜", "soon"],
      ["▶️", "play"],
      ["⏸️", "pause"],
      ["⏹️", "stop"],
      ["⏩", "fast forward"],
      ["⏪", "rewind"],
      ["⏺️", "record"],
      ["🔴", "red circle"],
      ["🟠", "orange circle"],
      ["🟡", "yellow circle"],
      ["🟢", "green circle"],
      ["🔵", "blue circle"],
      ["🟣", "purple circle"],
      ["⚫", "black circle"],
      ["⚪", "white circle"],
      ["🟥", "red square"],
      ["🟩", "green square"],
      ["⬛", "black square"],
      ["⬜", "white square"],
      ["🔺", "triangle up"],
      ["🔻", "triangle down"],
      ["💠", "diamond"],
      ["©️", "copyright"],
      ["™️", "trademark"],
    ],
  },
  {
    label: "Work and objects",
    rows: [
      ["💻", "laptop", "computer"],
      ["🖥️", "desktop", "monitor"],
      ["⌨️", "keyboard"],
      ["🖱️", "mouse"],
      ["📱", "phone", "mobile"],
      ["🎬", "clapper", "film", "action"],
      ["🎥", "movie camera", "film"],
      ["📽️", "projector"],
      ["🎞️", "film frames"],
      ["📷", "camera", "photo"],
      ["📸", "camera flash"],
      ["🎨", "palette", "art", "design"],
      ["🖌️", "paintbrush"],
      ["🖍️", "crayon"],
      ["✏️", "pencil", "write"],
      ["🖊️", "pen"],
      ["📝", "memo", "note", "write"],
      ["📓", "notebook", "journal"],
      ["📚", "books", "learn"],
      ["📖", "open book", "read"],
      ["📄", "page", "document"],
      ["📋", "clipboard"],
      ["📌", "pin"],
      ["📍", "location", "pin"],
      ["📎", "paperclip"],
      ["✂️", "scissors", "cut"],
      ["📐", "triangle ruler"],
      ["📏", "ruler"],
      ["🧮", "abacus"],
      ["📊", "bar chart", "stats"],
      ["📈", "chart up", "growth"],
      ["📉", "chart down"],
      ["💡", "idea", "light bulb"],
      ["🔦", "flashlight"],
      ["🔍", "magnifier", "search"],
      ["🔎", "magnifier right"],
      ["🔬", "microscope"],
      ["🔭", "telescope"],
      ["🧭", "compass"],
      ["⏰", "alarm", "clock"],
      ["⏳", "hourglass", "time"],
      ["⌛", "hourglass done"],
      ["⏱️", "stopwatch"],
      ["🗓️", "calendar"],
      ["📅", "calendar date"],
      ["🗂️", "folders"],
      ["📁", "folder"],
      ["📦", "package", "box"],
      ["📬", "mailbox"],
      ["✉️", "envelope", "email"],
      ["📣", "megaphone", "announce"],
      ["📢", "loudspeaker"],
      ["🔊", "speaker"],
      ["🎧", "headphones", "music"],
      ["🎵", "music note"],
      ["🎶", "notes", "music"],
      ["🎤", "microphone", "mic"],
      ["🎯", "target", "bullseye", "goal"],
      ["🏆", "trophy", "win"],
      ["🥇", "gold medal", "first"],
      ["🎖️", "medal"],
      ["🎁", "gift", "present"],
      ["🎉", "party popper", "celebrate"],
      ["🎊", "confetti"],
      ["🎈", "balloon"],
      ["🪄", "magic wand"],
      ["🔮", "crystal ball"],
      ["🧩", "puzzle"],
      ["🎮", "game", "controller"],
      ["🕹️", "joystick"],
      ["🎲", "dice"],
      ["♟️", "chess"],
      ["🪞", "mirror"],
      ["💎", "gem", "diamond"],
      ["💰", "money bag"],
      ["💸", "money flying", "spend"],
      ["💵", "dollar"],
      ["💳", "credit card"],
      ["🧾", "receipt"],
      ["⚙️", "gear", "settings"],
      ["🔧", "wrench", "fix"],
      ["🔨", "hammer", "build"],
      ["🛠️", "tools"],
      ["🧲", "magnet"],
      ["🪜", "ladder"],
      ["🧱", "brick", "build"],
      ["🚀", "rocket", "launch", "ship"],
      ["🛸", "ufo"],
      ["✈️", "plane", "travel"],
      ["🚗", "car"],
      ["🚲", "bicycle"],
      ["🏠", "house", "home"],
      ["🏢", "office"],
      ["🌍", "earth", "world", "globe"],
      ["🗺️", "map"],
      ["🧳", "luggage", "travel"],
    ],
  },
  {
    label: "Nature and food",
    rows: [
      ["🌱", "seedling", "grow"],
      ["🌿", "herb", "leaf"],
      ["🍀", "clover", "luck"],
      ["🌲", "evergreen", "tree"],
      ["🌳", "tree"],
      ["🌴", "palm"],
      ["🌵", "cactus"],
      ["🌸", "blossom", "flower"],
      ["🌻", "sunflower"],
      ["🌹", "rose"],
      ["🍁", "maple leaf", "autumn"],
      ["🍂", "fallen leaf"],
      ["🍃", "leaf wind"],
      ["🌊", "wave", "ocean"],
      ["🌋", "volcano"],
      ["⛰️", "mountain"],
      ["🏔️", "snowy mountain"],
      ["🐶", "dog"],
      ["🐱", "cat"],
      ["🐭", "mouse"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🦁", "lion"],
      ["🐯", "tiger"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🦉", "owl"],
      ["🦄", "unicorn"],
      ["🐝", "bee"],
      ["🦋", "butterfly"],
      ["🐢", "turtle", "slow"],
      ["🐍", "snake"],
      ["🐙", "octopus"],
      ["🐬", "dolphin"],
      ["🐳", "whale"],
      ["🦈", "shark"],
      ["🦖", "dinosaur", "t-rex"],
      ["🍎", "apple"],
      ["🍋", "lemon"],
      ["🍓", "strawberry"],
      ["🍉", "watermelon"],
      ["🍑", "peach"],
      ["🥑", "avocado"],
      ["🌶️", "chili", "hot"],
      ["🍕", "pizza"],
      ["🍔", "burger"],
      ["🌮", "taco"],
      ["🍜", "noodles", "ramen"],
      ["🍣", "sushi"],
      ["🍪", "cookie"],
      ["🍩", "donut"],
      ["🎂", "cake", "birthday"],
      ["🍫", "chocolate"],
      ["🍿", "popcorn"],
      ["☕", "coffee"],
      ["🍵", "tea"],
      ["🧉", "mate", "yerba"],
      ["🍺", "beer"],
      ["🍷", "wine"],
      ["🥂", "cheers", "toast"],
      ["🧃", "juice"],
    ],
  },
  {
    label: "People and flags",
    rows: [
      ["🧑‍💻", "technologist", "coder"],
      ["🧑‍🎨", "artist"],
      ["🧑‍🏫", "teacher"],
      ["🧑‍🎓", "student", "graduate"],
      ["🧑‍🚀", "astronaut"],
      ["🧑‍🔬", "scientist"],
      ["🧑‍🍳", "cook", "chef"],
      ["🧑‍🎤", "singer"],
      ["🕵️", "detective"],
      ["🧙", "wizard", "mage"],
      ["🦸", "superhero"],
      ["🧘", "meditate", "yoga", "lotus"],
      ["🏃", "running", "runner"],
      ["🚶", "walking"],
      ["🤷", "shrug"],
      ["🤦", "facepalm"],
      ["🙋", "raising hand"],
      ["💁", "tipping hand", "info"],
      ["🙇", "bow"],
      ["👨‍👩‍👧", "family"],
      ["👥", "people", "silhouettes"],
      ["🗣️", "speaking head", "talk"],
      ["💬", "speech bubble", "comment"],
      ["💭", "thought bubble"],
      ["🇺🇾", "uruguay"],
      ["🇪🇸", "spain"],
      ["🇬🇧", "uk", "britain"],
      ["🇺🇸", "usa"],
      ["🇦🇷", "argentina"],
      ["🇧🇷", "brazil"],
      ["🇲🇽", "mexico"],
      ["🇩🇪", "germany"],
      ["🇫🇷", "france"],
      ["🇮🇹", "italy"],
      ["🇵🇹", "portugal"],
      ["🏳️‍🌈", "pride", "rainbow flag"],
      ["🏁", "chequered flag", "finish"],
      ["🚩", "red flag"],
    ],
  },
];

/** Every emoji whose words contain the query, or every emoji for an empty
 *  one, kept in the picker's own order. */
export function searchEmoji(query: string): string[][] {
  const q = query.trim().toLowerCase();
  const all = EMOJI.flatMap((g) => g.rows);
  if (!q) return all;
  return all.filter((row) => row.slice(1).some((w) => w.includes(q)));
}
